services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - YPAREO_BASE_URL=${YPAREO_BASE_URL}
      - YPAREO_TOKEN=${YPAREO_TOKEN}
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    restart: unless-stopped
    command: npx ts-node-dev --respawn src/index.ts